
import React from 'react';

interface ImageResultProps {
  src: string;
}

const ImageResult: React.FC<ImageResultProps> = ({ src }) => (
  <div className="w-full h-full p-2 flex items-center justify-center">
    <img
      src={src}
      alt="Generated by AI"
      className="max-w-full max-h-full object-contain rounded-lg shadow-lg"
    />
  </div>
);

export default ImageResult;
