import React from 'react';

interface ImageResultProps {
  src: string;
  prompt: string;
  index: number;
}

const ImageResult: React.FC<ImageResultProps> = ({ src, prompt, index }) => {
    const handleDownload = () => {
        const link = document.createElement('a');
        link.href = src;
        
        const safePrompt = (prompt.trim().toLowerCase()
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .slice(0, 50)) || 'ai-vision';
        const filename = `${safePrompt}-${index + 1}.png`;

        link.download = filename;
        
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };
    
    return (
      <div className="relative w-full h-full group flex items-center justify-center">
        <img
          src={src}
          alt={`Generated by AI - result ${index + 1}`}
          className="max-w-full max-h-full object-contain rounded-lg shadow-lg animate-reveal"
        />
        <button
            onClick={handleDownload}
            className="absolute bottom-2 right-2 z-10 p-2 bg-black/50 rounded-full text-white hover:bg-purple-600/80 focus:outline-none focus:ring-2 focus:ring-purple-400 backdrop-blur-sm transition-all opacity-0 group-hover:opacity-100"
            aria-label={`Download image ${index + 1}`}
        >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
            </svg>
        </button>
      </div>
    );
};

export default ImageResult;
